# permissions for end users to view computenodegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: computenodegroup-viewer-role
rules:
- apiGroups:
  - starrocks.com
  resources:
  - computenodegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starrocks.com
  resources:
  - computenodegroups/status
  verbs:
  - get
