# permissions for end users to edit computenodegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: computenodegroup-editor-role
rules:
- apiGroups:
  - starrocks.com
  resources:
  - computenodegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starrocks.com
  resources:
  - computenodegroups/status
  verbs:
  - get
