apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cn-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cn-manager-role
subjects:
- kind: ServiceAccount
  name: cn-controller-manager
  namespace: starrocks
