apiVersion: starrocks.com/v1alpha1
kind: ComputeNodeGroup
metadata:
  name: computenodegroup-sample
  namespace: starrocks
  annotations:
    # assign a public ip to cn-pod, here we use the vpc-cni(https://cloud.tencent.com/document/product/457/50357)
    tke.cloud.tencent.com/networks: tke-direct-eni
spec:
  cnInfo:
    configMap: cn-test # configmap to configure CN
  feInfo:
    accountSecret: test-secret # secret to configure FE account
    addresses: # FE addresses
      - <ip>:<port>
  images:
    cnImage: xxx:xxx # CN image
    componentsImage: xxx:xxx # auxiliary components image
  replicas: 4 # replicas of CN
  cronJobPolicy:
    schedule: "*/1 * * * *" # cron expression of offline-job
  podPolicy:
    resources: # resources requirement of CN pod
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 4000m
        memory: 8Gi
  autoScalingPolicy: # auto-scaling policy of CN cluster
    maxReplicas: 10
    minReplicas: 1
    hpaPolicy:
      metrics: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#metricspec-v2beta2-autoscaling
        - type: Resource
          resource:
            name: memory
            target:
              averageUtilization: 30
              type: Utilization
        - type: Resource
          resource:
            name: cpu
            target:
              averageUtilization: 30
              type: Utilization
      behavior: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#horizontalpodautoscalerbehavior-v2beta2-autoscaling
        scaleUp:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 10
        scaleDown:
          selectPolicy: Disabled